

CREATE DATABASE d_order;


CREATE TABLE d_order.t_order (
	id BIGINT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id BIGINT(11) NOT NULL,
	money DECIMAL(11,0) NOT NULL,
	status INT(1) DEFAULT 0 COMMENT '訂單狀態 0:執行中 1:成功 2:失敗',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;