server:
  port: 8090

spring:
  application:
    name: order-service
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 127.0.0.1:8848

      discovery:
        username: nacos
        password: nacos
        enabled: true
        server-addr: 127.0.0.1:8848
        register-enabled: true
    alibaba:
      seata:
        tx-service-group: my_test_tx_group




  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://db:3306/d_order?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    url: jdbc:mysql://127.0.0.1:3310/d_order?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    username: root
    password: 123456

log4j:
  category:
    org:
      springframework:
        jdbc:
          core: TRACE
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework: INFO
      example:
        orderService:
          dao: DEBUG
    io:
      seata: debug

feign:
  client:
    config:
      default:
        loggerLevel: full

ribbon:
  ReadTimeout: 60000      # 60秒
  ConnectTimeout: 60000   # 60秒

